GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlrYXMyIiwiaWF0IjoxNjc0NzUyMDY2LCJleHAiOjE2NzQ3NTIwODF9.JDFkt6t-8J_7XlJtq5tezkQI7m4xrdVg88ZZ_uldisc
###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlrYXMyIiwiaWF0IjoxNjc0NzUyMDUwfQ.Gu6ys-qp07_aQxWv_rhGEFe6KzVIHf010JkaavWcPmU"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlrYXMyIiwiaWF0IjoxNjc0NzUyNDM4fQ.L_ON4dkvBVee8xeShLH4b2h_8-URV0prKRmQxTIw7tY"
}

###
POST http://localhost:4000/login  
#Should be sent first as jwt needs to create token for the user
Content-Type: application/json

{
    "username" : "Vikas2"
}